package gov.nih.nci.ncicb.cadsr.persistence.bc4j;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class HistoricalCdeIdsViewImpl extends ViewObjectImpl  {
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public HistoricalCdeIdsViewImpl() {
  }
}