package gov.nih.nci.ncicb.cadsr.persistence.bc4j;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.RowIterator;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ValidValuesViewRowImpl extends ViewRowImpl 
{


  protected static final int SHORTMEANING = 0;
  protected static final int DESCRIPTION = 1;
  protected static final int VALUE = 2;
  protected static final int PVIDSEQ = 3;
  protected static final int VDIDSEQ = 4;
  protected static final int MEANINGDESCRIPTION = 5;
  protected static final int VPIDSEQ = 6;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ValidValuesViewRowImpl()
  {
  }

  /**
   * 
   * Gets VdPvs entity object.
   */
  public VdPvsImpl getVdPvs()
  {
    return (VdPvsImpl)getEntity(0);
  }

  /**
   * 
   * Gets ValueMeaningsLov entity object.
   */
  public ValueMeaningsLovImpl getValueMeaningsLov()
  {
    return (ValueMeaningsLovImpl)getEntity(1);
  }

  /**
   * 
   * Gets ValueDomains entity object.
   */
  public ValueDomainsImpl getValueDomains()
  {
    return (ValueDomainsImpl)getEntity(2);
  }

  /**
   * 
   * Gets PermissibleValues entity object.
   */
  public PermissibleValuesImpl getPermissibleValues()
  {
    return (PermissibleValuesImpl)getEntity(3);
  }

  /**
   * 
   * Gets the attribute value for SHORT_MEANING using the alias name ShortMeaning
   */
  public String getShortMeaning()
  {
    return (String)getAttributeInternal(SHORTMEANING);
  }

  /**
   * 
   * Gets the attribute value for DESCRIPTION using the alias name Description
   */
  public String getDescription()
  {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  /**
   * 
   * Gets the attribute value for VALUE using the alias name Value
   */
  public String getValue()
  {
    return (String)getAttributeInternal(VALUE);
  }


  /**
   * 
   * Gets the attribute value for MEANING_DESCRIPTION using the alias name MeaningDescription
   */
  public String getMeaningDescription()
  {
    return (String)getAttributeInternal(MEANINGDESCRIPTION);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case SHORTMEANING:
        return getShortMeaning();
      case DESCRIPTION:
        return getDescription();
      case VALUE:
        return getValue();
      case PVIDSEQ:
        return getPvIdseq();
      case VDIDSEQ:
        return getVdIdseq();
      case MEANINGDESCRIPTION:
        return getMeaningDescription();
      case VPIDSEQ:
        return getVpIdseq();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case VPIDSEQ:
        setVpIdseq((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }



  /**
   * 
   * Gets the attribute value for PV_IDSEQ using the alias name PvIdseq
   */
  public String getPvIdseq()
  {
    return (String)getAttributeInternal(PVIDSEQ);
  }

  /**
   * 
   * Gets the attribute value for VD_IDSEQ using the alias name VdIdseq
   */
  public String getVdIdseq()
  {
    return (String)getAttributeInternal(VDIDSEQ);
  }

  /**
   * 
   * Gets the attribute value for VP_IDSEQ using the alias name VpIdseq
   */
  public String getVpIdseq() {
    return (String)getAttributeInternal(VPIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for VP_IDSEQ using the alias name VpIdseq
   */
  public void setVpIdseq(String value) {
    setAttributeInternal(VPIDSEQ, value);
  }


}