package gov.nih.nci.ncicb.cadsr.persistence.bc4j.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class CompConceptsViewObjRowClient extends RowImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public CompConceptsViewObjRowClient()
  {
  }

  public String getConIdseq()
  {
    return (String)getAttribute("ConIdseq");
  }

  public void setConIdseq(String param0)
  {
    setAttribute("ConIdseq", param0);
  }

  public String getPreferredName()
  {
    return (String)getAttribute("PreferredName");
  }

  public void setPreferredName(String param0)
  {
    setAttribute("PreferredName", param0);
  }

  public String getLongName()
  {
    return (String)getAttribute("LongName");
  }

  public void setLongName(String param0)
  {
    setAttribute("LongName", param0);
  }

  public String getPreferredDefinition()
  {
    return (String)getAttribute("PreferredDefinition");
  }

  public void setPreferredDefinition(String param0)
  {
    setAttribute("PreferredDefinition", param0);
  }

  public String getConteIdseq()
  {
    return (String)getAttribute("ConteIdseq");
  }

  public void setConteIdseq(String param0)
  {
    setAttribute("ConteIdseq", param0);
  }

  public oracle.jbo.domain.Number getVersion()
  {
    return (oracle.jbo.domain.Number)getAttribute("Version");
  }

  public void setVersion(oracle.jbo.domain.Number param0)
  {
    setAttribute("Version", param0);
  }

  public String getAslName()
  {
    return (String)getAttribute("AslName");
  }

  public void setAslName(String param0)
  {
    setAttribute("AslName", param0);
  }

  public String getLatestVersionInd()
  {
    return (String)getAttribute("LatestVersionInd");
  }

  public void setLatestVersionInd(String param0)
  {
    setAttribute("LatestVersionInd", param0);
  }

  public String getDefinitionSource()
  {
    return (String)getAttribute("DefinitionSource");
  }

  public void setDefinitionSource(String param0)
  {
    setAttribute("DefinitionSource", param0);
  }

  public oracle.jbo.domain.Number getConId()
  {
    return (oracle.jbo.domain.Number)getAttribute("ConId");
  }

  public void setConId(oracle.jbo.domain.Number param0)
  {
    setAttribute("ConId", param0);
  }

  public String getEvsSource()
  {
    return (String)getAttribute("EvsSource");
  }

  public void setEvsSource(String param0)
  {
    setAttribute("EvsSource", param0);
  }

  public String getCondrIdseq()
  {
    return (String)getAttribute("CondrIdseq");
  }

  public void setCondrIdseq(String param0)
  {
    setAttribute("CondrIdseq", param0);
  }

  public String getCcIdseq()
  {
    return (String)getAttribute("CcIdseq");
  }

  public void setCcIdseq(String param0)
  {
    setAttribute("CcIdseq", param0);
  }
}