package gov.nih.nci.ncicb.cadsr.persistence.bc4j;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class CompConceptsViewObjImpl extends ViewObjectImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public CompConceptsViewObjImpl()
  {
  }
}