package gov.nih.nci.ncicb.cadsr.persistence.bc4j;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CsCsiViewRowImpl extends ViewRowImpl 
{


  public static final int CSCSIIDSEQ = 0;
  public static final int CSIDSEQ = 1;
  public static final int CSIIDSEQ = 2;
  public static final int PCSCSIIDSEQ = 3;
  public static final int LINKCSCSIIDSEQ = 4;
  public static final int LABEL = 5;
  public static final int DISPLAYORDER = 6;
  public static final int DATECREATED = 7;
  public static final int CREATEDBY = 8;
  public static final int DATEMODIFIED = 9;
  public static final int MODIFIEDBY = 10;
  public static final int CLASSIFICATIONSCHEMESVIEW = 11;
  public static final int CLASSSCHEMEITEMSVIEW = 12;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public CsCsiViewRowImpl()
  {
  }

  /**
   * 
   * Gets CsCsi entity object.
   */
  public CsCsiImpl getCsCsi()
  {
    return (CsCsiImpl)getEntity(0);
  }

  /**
   * 
   * Gets the attribute value for CS_CSI_IDSEQ using the alias name CsCsiIdseq
   */
  public String getCsCsiIdseq()
  {
    return (String)getAttributeInternal(CSCSIIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CS_CSI_IDSEQ using the alias name CsCsiIdseq
   */
  public void setCsCsiIdseq(String value)
  {
    setAttributeInternal(CSCSIIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for CS_IDSEQ using the alias name CsIdseq
   */
  public String getCsIdseq()
  {
    return (String)getAttributeInternal(CSIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CS_IDSEQ using the alias name CsIdseq
   */
  public void setCsIdseq(String value)
  {
    setAttributeInternal(CSIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for CSI_IDSEQ using the alias name CsiIdseq
   */
  public String getCsiIdseq()
  {
    return (String)getAttributeInternal(CSIIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CSI_IDSEQ using the alias name CsiIdseq
   */
  public void setCsiIdseq(String value)
  {
    setAttributeInternal(CSIIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for P_CS_CSI_IDSEQ using the alias name PCsCsiIdseq
   */
  public String getPCsCsiIdseq()
  {
    return (String)getAttributeInternal(PCSCSIIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for P_CS_CSI_IDSEQ using the alias name PCsCsiIdseq
   */
  public void setPCsCsiIdseq(String value)
  {
    setAttributeInternal(PCSCSIIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for LINK_CS_CSI_IDSEQ using the alias name LinkCsCsiIdseq
   */
  public String getLinkCsCsiIdseq()
  {
    return (String)getAttributeInternal(LINKCSCSIIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LINK_CS_CSI_IDSEQ using the alias name LinkCsCsiIdseq
   */
  public void setLinkCsCsiIdseq(String value)
  {
    setAttributeInternal(LINKCSCSIIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for LABEL using the alias name Label
   */
  public String getLabel()
  {
    return (String)getAttributeInternal(LABEL);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LABEL using the alias name Label
   */
  public void setLabel(String value)
  {
    setAttributeInternal(LABEL, value);
  }

  /**
   * 
   * Gets the attribute value for DISPLAY_ORDER using the alias name DisplayOrder
   */
  public Number getDisplayOrder()
  {
    return (Number)getAttributeInternal(DISPLAYORDER);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DISPLAY_ORDER using the alias name DisplayOrder
   */
  public void setDisplayOrder(Number value)
  {
    setAttributeInternal(DISPLAYORDER, value);
  }

  /**
   * 
   * Gets the attribute value for DATE_CREATED using the alias name DateCreated
   */
  public Date getDateCreated()
  {
    return (Date)getAttributeInternal(DATECREATED);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DATE_CREATED using the alias name DateCreated
   */
  public void setDateCreated(Date value)
  {
    setAttributeInternal(DATECREATED, value);
  }

  /**
   * 
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy
   */
  public String getCreatedBy()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
   */
  public void setCreatedBy(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for DATE_MODIFIED using the alias name DateModified
   */
  public Date getDateModified()
  {
    return (Date)getAttributeInternal(DATEMODIFIED);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DATE_MODIFIED using the alias name DateModified
   */
  public void setDateModified(Date value)
  {
    setAttributeInternal(DATEMODIFIED, value);
  }

  /**
   * 
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy
   */
  public String getModifiedBy()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy
   */
  public void setModifiedBy(String value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CSCSIIDSEQ:
        return getCsCsiIdseq();
      case CSIDSEQ:
        return getCsIdseq();
      case CSIIDSEQ:
        return getCsiIdseq();
      case PCSCSIIDSEQ:
        return getPCsCsiIdseq();
      case LINKCSCSIIDSEQ:
        return getLinkCsCsiIdseq();
      case LABEL:
        return getLabel();
      case DISPLAYORDER:
        return getDisplayOrder();
      case DATECREATED:
        return getDateCreated();
      case CREATEDBY:
        return getCreatedBy();
      case DATEMODIFIED:
        return getDateModified();
      case MODIFIEDBY:
        return getModifiedBy();
      case CLASSIFICATIONSCHEMESVIEW:
        return getClassificationSchemesView();
      case CLASSSCHEMEITEMSVIEW:
        return getClassSchemeItemsView();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CSCSIIDSEQ:
        setCsCsiIdseq((String)value);
        return;
      case CSIDSEQ:
        setCsIdseq((String)value);
        return;
      case CSIIDSEQ:
        setCsiIdseq((String)value);
        return;
      case PCSCSIIDSEQ:
        setPCsCsiIdseq((String)value);
        return;
      case LINKCSCSIIDSEQ:
        setLinkCsCsiIdseq((String)value);
        return;
      case LABEL:
        setLabel((String)value);
        return;
      case DISPLAYORDER:
        setDisplayOrder((Number)value);
        return;
      case DATECREATED:
        setDateCreated((Date)value);
        return;
      case CREATEDBY:
        setCreatedBy((String)value);
        return;
      case DATEMODIFIED:
        setDateModified((Date)value);
        return;
      case MODIFIEDBY:
        setModifiedBy((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the associated <code>Row</code> using master-detail link ClassificationSchemesView
   */
  public oracle.jbo.Row getClassificationSchemesView() {
    return (oracle.jbo.Row)getAttributeInternal(CLASSIFICATIONSCHEMESVIEW);
  }

  /**
   * 
   * Gets the associated <code>Row</code> using master-detail link ClassSchemeItemsView
   */
  public oracle.jbo.Row getClassSchemeItemsView() {
    return (oracle.jbo.Row)getAttributeInternal(CLASSSCHEMEITEMSVIEW);
  }
}