package gov.nih.nci.ncicb.cadsr.persistence.bc4j;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class DesignationsViewRowImpl extends ViewRowImpl  {


  public static final int DESIGIDSEQ = 0;
  public static final int ACIDSEQ = 1;
  public static final int CONTEIDSEQ = 2;
  public static final int NAME = 3;
  public static final int DETLNAME = 4;
  public static final int DATECREATED = 5;
  public static final int CREATEDBY = 6;
  public static final int DATEMODIFIED = 7;
  public static final int MODIFIEDBY = 8;
  public static final int LAENAME = 9;
  public static final int CONTEXTSROW = 10;
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public DesignationsViewRowImpl() {
  }

  /**
   * 
   * Gets Designations entity object.
   */
  public DesignationsImpl getDesignations() {
    return (DesignationsImpl)getEntity(0);
  }

  /**
   * 
   * Gets the attribute value for DESIG_IDSEQ using the alias name DesigIdseq
   */
  public String getDesigIdseq() {
    return (String)getAttributeInternal(DESIGIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DESIG_IDSEQ using the alias name DesigIdseq
   */
  public void setDesigIdseq(String value) {
    setAttributeInternal(DESIGIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for AC_IDSEQ using the alias name AcIdseq
   */
  public String getAcIdseq() {
    return (String)getAttributeInternal(ACIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for AC_IDSEQ using the alias name AcIdseq
   */
  public void setAcIdseq(String value) {
    setAttributeInternal(ACIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for CONTE_IDSEQ using the alias name ConteIdseq
   */
  public String getConteIdseq() {
    return (String)getAttributeInternal(CONTEIDSEQ);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CONTE_IDSEQ using the alias name ConteIdseq
   */
  public void setConteIdseq(String value) {
    setAttributeInternal(CONTEIDSEQ, value);
  }

  /**
   * 
   * Gets the attribute value for NAME using the alias name Name
   */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for NAME using the alias name Name
   */
  public void setName(String value) {
    setAttributeInternal(NAME, value);
  }

  /**
   * 
   * Gets the attribute value for DETL_NAME using the alias name DetlName
   */
  public String getDetlName() {
    return (String)getAttributeInternal(DETLNAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DETL_NAME using the alias name DetlName
   */
  public void setDetlName(String value) {
    setAttributeInternal(DETLNAME, value);
  }

  /**
   * 
   * Gets the attribute value for DATE_CREATED using the alias name DateCreated
   */
  public Date getDateCreated() {
    return (Date)getAttributeInternal(DATECREATED);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DATE_CREATED using the alias name DateCreated
   */
  public void setDateCreated(Date value) {
    setAttributeInternal(DATECREATED, value);
  }

  /**
   * 
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy
   */
  public String getCreatedBy() {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
   */
  public void setCreatedBy(String value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for DATE_MODIFIED using the alias name DateModified
   */
  public Date getDateModified() {
    return (Date)getAttributeInternal(DATEMODIFIED);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for DATE_MODIFIED using the alias name DateModified
   */
  public void setDateModified(Date value) {
    setAttributeInternal(DATEMODIFIED, value);
  }

  /**
   * 
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy
   */
  public String getModifiedBy() {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy
   */
  public void setModifiedBy(String value) {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * 
   * Gets the attribute value for LAE_NAME using the alias name LaeName
   */
  public String getLaeName() {
    return (String)getAttributeInternal(LAENAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LAE_NAME using the alias name LaeName
   */
  public void setLaeName(String value) {
    setAttributeInternal(LAENAME, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    switch (index)
      {
      case DESIGIDSEQ:
        return getDesigIdseq();
      case ACIDSEQ:
        return getAcIdseq();
      case CONTEIDSEQ:
        return getConteIdseq();
      case NAME:
        return getName();
      case DETLNAME:
        return getDetlName();
      case DATECREATED:
        return getDateCreated();
      case CREATEDBY:
        return getCreatedBy();
      case DATEMODIFIED:
        return getDateModified();
      case MODIFIEDBY:
        return getModifiedBy();
      case LAENAME:
        return getLaeName();
      case CONTEXTSROW:
        return getContextsRow();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
    switch (index)
      {
      case DESIGIDSEQ:
        setDesigIdseq((String)value);
        return;
      case ACIDSEQ:
        setAcIdseq((String)value);
        return;
      case CONTEIDSEQ:
        setConteIdseq((String)value);
        return;
      case NAME:
        setName((String)value);
        return;
      case DETLNAME:
        setDetlName((String)value);
        return;
      case DATECREATED:
        setDateCreated((Date)value);
        return;
      case CREATEDBY:
        setCreatedBy((String)value);
        return;
      case DATEMODIFIED:
        setDateModified((Date)value);
        return;
      case MODIFIEDBY:
        setModifiedBy((String)value);
        return;
      case LAENAME:
        setLaeName((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Gets the associated <code>Row</code> using master-detail link ContextsRow
   */
  public oracle.jbo.Row getContextsRow() {
    return (oracle.jbo.Row)getAttributeInternal(CONTEXTSROW);
  }

  
}