package gov.nih.nci.ncicb.cadsr.common.persistence.bc4j;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.jbo.Key;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class ComponentConceptsExtImpl extends EntityImpl 
{
  public static final int CCIDSEQ = 0;
  public static final int CONDRIDSEQ = 1;
  public static final int CONIDSEQ = 2;
  public static final int DISPLAYORDER = 3;
  public static final int DATECREATED = 4;
  public static final int DATEMODIFIED = 5;
  public static final int MODIFIEDBY = 6;
  public static final int CREATEDBY = 7;
  public static final int CONCEPTSEXT = 8;
  public static final int CONDERIVATIONRULESEXT = 9;


  private static EntityDefImpl mDefinitionObject;

  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public ComponentConceptsExtImpl()
  {
  }

  /**
   * 
   *  Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("gov.nih.nci.ncicb.cadsr.common.persistence.bc4j.ComponentConceptsExt");
    }
    return mDefinitionObject;
  }



  /**
   * 
   *  Gets the attribute value for CcIdseq, using the alias name CcIdseq
   */
  public String getCcIdseq()
  {
    return (String)getAttributeInternal(CCIDSEQ);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for CcIdseq
   */
  public void setCcIdseq(String value)
  {
    setAttributeInternal(CCIDSEQ, value);
  }

  /**
   * 
   *  Gets the attribute value for CondrIdseq, using the alias name CondrIdseq
   */
  public String getCondrIdseq()
  {
    return (String)getAttributeInternal(CONDRIDSEQ);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for CondrIdseq
   */
  public void setCondrIdseq(String value)
  {
    setAttributeInternal(CONDRIDSEQ, value);
  }

  /**
   * 
   *  Gets the attribute value for ConIdseq, using the alias name ConIdseq
   */
  public String getConIdseq()
  {
    return (String)getAttributeInternal(CONIDSEQ);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for ConIdseq
   */
  public void setConIdseq(String value)
  {
    setAttributeInternal(CONIDSEQ, value);
  }

  /**
   * 
   *  Gets the attribute value for DisplayOrder, using the alias name DisplayOrder
   */
  public Number getDisplayOrder()
  {
    return (Number)getAttributeInternal(DISPLAYORDER);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for DisplayOrder
   */
  public void setDisplayOrder(Number value)
  {
    setAttributeInternal(DISPLAYORDER, value);
  }

  /**
   * 
   *  Gets the attribute value for DateCreated, using the alias name DateCreated
   */
  public Date getDateCreated()
  {
    return (Date)getAttributeInternal(DATECREATED);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for DateCreated
   */
  public void setDateCreated(Date value)
  {
    setAttributeInternal(DATECREATED, value);
  }

  /**
   * 
   *  Gets the attribute value for DateModified, using the alias name DateModified
   */
  public Date getDateModified()
  {
    return (Date)getAttributeInternal(DATEMODIFIED);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for DateModified
   */
  public void setDateModified(Date value)
  {
    setAttributeInternal(DATEMODIFIED, value);
  }

  /**
   * 
   *  Gets the attribute value for ModifiedBy, using the alias name ModifiedBy
   */
  public String getModifiedBy()
  {
    return (String)getAttributeInternal(MODIFIEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for ModifiedBy
   */
  public void setModifiedBy(String value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * 
   *  Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public String getCreatedBy()
  {
    return (String)getAttributeInternal(CREATEDBY);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(String value)
  {
    setAttributeInternal(CREATEDBY, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CCIDSEQ:
        return getCcIdseq();
      case CONDRIDSEQ:
        return getCondrIdseq();
      case CONIDSEQ:
        return getConIdseq();
      case DISPLAYORDER:
        return getDisplayOrder();
      case DATECREATED:
        return getDateCreated();
      case DATEMODIFIED:
        return getDateModified();
      case MODIFIEDBY:
        return getModifiedBy();
      case CREATEDBY:
        return getCreatedBy();
      case CONCEPTSEXT:
        return getConceptsExt();
      case CONDERIVATIONRULESEXT:
        return getConDerivationRulesExt();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CCIDSEQ:
        setCcIdseq((String)value);
        return;
      case CONDRIDSEQ:
        setCondrIdseq((String)value);
        return;
      case CONIDSEQ:
        setConIdseq((String)value);
        return;
      case DISPLAYORDER:
        setDisplayOrder((Number)value);
        return;
      case DATECREATED:
        setDateCreated((Date)value);
        return;
      case DATEMODIFIED:
        setDateModified((Date)value);
        return;
      case MODIFIEDBY:
        setModifiedBy((String)value);
        return;
      case CREATEDBY:
        setCreatedBy((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   *  Gets the associated entity ConceptsExtImpl
   */
  public ConceptsExtImpl getConceptsExt()
  {
    return (ConceptsExtImpl)getAttributeInternal(CONCEPTSEXT);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity ConceptsExtImpl
   */
  public void setConceptsExt(ConceptsExtImpl value)
  {
    setAttributeInternal(CONCEPTSEXT, value);
  }


  /**
   * 
   *  Gets the associated entity ConDerivationRulesExtImpl
   */
  public ConDerivationRulesExtImpl getConDerivationRulesExt()
  {
    return (ConDerivationRulesExtImpl)getAttributeInternal(CONDERIVATIONRULESEXT);
  }

  /**
   * 
   *  Sets <code>value</code> as the associated entity ConDerivationRulesExtImpl
   */
  public void setConDerivationRulesExt(ConDerivationRulesExtImpl value)
  {
    setAttributeInternal(CONDERIVATIONRULESEXT, value);
  }

  /**
   * 
   *  Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String ccIdseq)
  {
    return new Key(new Object[] {ccIdseq});
  }


}