package gov.nih.nci.ncicb.cadsr.common.persistence.bc4j;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class FormModuleRelViewImpl extends ViewObjectImpl  {
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public FormModuleRelViewImpl() {
  }
}